Comenta la configuración del flujo de trabajo de publicación en publish.yml

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,39 +1,39 @@
-name: publish
+# name: publish
 
-on:
-  push:
-    branches: ['dev']
+# on:
+#   push:
+#     branches: ['dev']
 
-jobs:
-  create-docker-image:
-    runs-on: ubuntu-22.04
-    steps:
-      - name: Checkout the code
-        uses: actions/checkout@v2
+# jobs:
+#   create-docker-image:
+#     runs-on: ubuntu-22.04
+#     steps:
+#       - name: Checkout the code
+#         uses: actions/checkout@v2
 
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v1
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GHCR_TOKEN }}
+#       - name: Login to GitHub Container Registry
+#         uses: docker/login-action@v1
+#         with:
+#           registry: ghcr.io
+#           username: ${{ github.actor }}
+#           password: ${{ secrets.GHCR_TOKEN }}
 
-      - name: Build deployment image
-        run: |
-          IMAGE=ghcr.io/luirrodev/smart-stock-hub-api
-          echo "Building deployment image using --target development..."
-          docker build --target development . --tag $IMAGE
-          echo "Pushing $IMAGE to registry..."
-          docker push $IMAGE
+#       - name: Build deployment image
+#         run: |
+#           IMAGE=ghcr.io/luirrodev/smart-stock-hub-api
+#           echo "Building deployment image using --target development..."
+#           docker build --target development . --tag $IMAGE
+#           echo "Pushing $IMAGE to registry..."
+#           docker push $IMAGE
 
-      - name: Deploy to Render
-        if: success() && github.ref == 'refs/heads/dev'
-        run: |
-          echo "Triggering deployment to Render..."
-          response=$(curl -s -o /dev/null -w "%{http_code}" -X GET "${{ secrets.RENDER_DEPLOY_HOOK }}")
-          if [ "$response" -eq 200 ]; then
-            echo "✅ Deployment triggered successfully!"
-          else
-            echo "❌ Failed to trigger deployment. HTTP status: $response"
-            exit 1
-          fi
+#       - name: Deploy to Render
+#         if: success() && github.ref == 'refs/heads/dev'
+#         run: |
+#           echo "Triggering deployment to Render..."
+#           response=$(curl -s -o /dev/null -w "%{http_code}" -X GET "${{ secrets.RENDER_DEPLOY_HOOK }}")
+#           if [ "$response" -eq 200 ]; then
+#             echo "✅ Deployment triggered successfully!"
+#           else
+#             echo "❌ Failed to trigger deployment. HTTP status: $response"
+#             exit 1
+#           fi
